# nixpacks.toml - Configuração de build para Railway
# Por: ULTRATHINK

[phases.setup]
nixPkgs = ['php81', 'php81Extensions.curl', 'php81Extensions.mbstring', 'php81Extensions.openssl', 'php81Extensions.pdo', 'php81Extensions.pdo_mysql', 'php81Extensions.tokenizer', 'php81Extensions.xml', 'php81Extensions.ctype', 'php81Extensions.json', 'php81Extensions.bcmath', 'php81Extensions.fileinfo', 'php81Extensions.gd', 'php81Extensions.intl', 'php81Extensions.zip', 'php81Extensions.dom', 'php81Extensions.session', 'php81Extensions.simplexml', 'php81Extensions.xmlwriter', 'php81Extensions.xmlreader', 'nodejs-18_x', 'mysql80']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'

[variables]
PHP_VERSION = '8.1'
NODE_VERSION = '18'
NIXPACKS_PHP_ROOT_DIR = '/app'
NIXPACKS_PHP_FALLBACK_PATH = '/app/public'